<?php
// Clean output buffering approach
ob_start();

// Suppress warnings for clean JSON output
error_reporting(E_ERROR | E_PARSE);
ini_set('display_errors', 0);

try {
    // Include required files
    require_once(__DIR__ . '/../../includes/shipping.php');

    // Clear any output generated by includes
    ob_clean();
    
    // Set JSON header
    header('Content-Type: application/json');

    // Validate request method
    if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
        throw new Exception('Only POST requests allowed');
    }

    // Get and validate inputs
    $country = $_POST['country'] ?? 'united arab emirates';
    $city = $_POST['city'] ?? '_';
    $totalWeight = isset($_POST['totalWeight']) ? floatval($_POST['totalWeight']) : 1;

    if (empty($country)) {
        throw new Exception('Country is required');
    }

    if ($totalWeight <= 0) {
        throw new Exception('Invalid weight');
    }

    // Check if function exists
    if (!function_exists('calculateShippingCost')) {
        throw new Exception('Function calculateShippingCost() not found');
    }

    // Calculate shipping cost
    $cost = calculateShippingCost($country, $city, $totalWeight);

    if (!is_numeric($cost) || $cost < 0) {
        throw new Exception('Invalid shipping cost: ' . var_export($cost, true));
    }

    // Return success response
    $response = [
        'success' => true,
        'country' => $country,
        'city' => $city,
        'totalWeight' => $totalWeight,
        'shippingAED' => number_format($cost, 2),
        'shippingCost' => $cost,
        'currency' => 'AED',
        'timestamp' => date('Y-m-d H:i:s')
    ];

    echo json_encode($response);

} catch (Exception $e) {
    // Return error response
    $response = [
        'success' => false,
        'error' => $e->getMessage(),
        'timestamp' => date('Y-m-d H:i:s')
    ];
    
    echo json_encode($response);
} catch (Error $e) {
    // Handle PHP fatal errors
    $response = [
        'success' => false,
        'error' => 'System error: ' . $e->getMessage(),
        'timestamp' => date('Y-m-d H:i:s')
    ];
    
    echo json_encode($response);
}

ob_end_flush();
exit;
